# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Matrix.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Matrix.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cMatrix.proto\"\xc8\x01\n\x0bProtoSquare\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.ProtoSquare.Coordinate\x12\r\n\x05value\x18\x02 \x01(\x05\x12+\n\nneighbours\x18\x03 \x03(\x0b\x32\x17.ProtoSquare.Coordinate\x12.\n\rnotNeighbours\x18\x04 \x03(\x0b\x32\x17.ProtoSquare.Coordinate\x1a\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\":\n\x0bProtoMatrix\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x1d\n\x07squares\x18\x02 \x03(\x0b\x32\x0c.ProtoSquare\"D\n\x10ProtoAllMatrices\x12\x10\n\x08quantity\x18\x01 \x01(\x05\x12\x1e\n\x08matrices\x18\x02 \x03(\x0b\x32\x0c.ProtoMatrixb\x06proto3')
)




_PROTOSQUARE_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='ProtoSquare.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ProtoSquare.Coordinate.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ProtoSquare.Coordinate.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=217,
)

_PROTOSQUARE = _descriptor.Descriptor(
  name='ProtoSquare',
  full_name='ProtoSquare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='ProtoSquare.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ProtoSquare.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbours', full_name='ProtoSquare.neighbours', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notNeighbours', full_name='ProtoSquare.notNeighbours', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTOSQUARE_COORDINATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=217,
)


_PROTOMATRIX = _descriptor.Descriptor(
  name='ProtoMatrix',
  full_name='ProtoMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='ProtoMatrix.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squares', full_name='ProtoMatrix.squares', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=277,
)


_PROTOALLMATRICES = _descriptor.Descriptor(
  name='ProtoAllMatrices',
  full_name='ProtoAllMatrices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity', full_name='ProtoAllMatrices.quantity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matrices', full_name='ProtoAllMatrices.matrices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=347,
)

_PROTOSQUARE_COORDINATE.containing_type = _PROTOSQUARE
_PROTOSQUARE.fields_by_name['position'].message_type = _PROTOSQUARE_COORDINATE
_PROTOSQUARE.fields_by_name['neighbours'].message_type = _PROTOSQUARE_COORDINATE
_PROTOSQUARE.fields_by_name['notNeighbours'].message_type = _PROTOSQUARE_COORDINATE
_PROTOMATRIX.fields_by_name['squares'].message_type = _PROTOSQUARE
_PROTOALLMATRICES.fields_by_name['matrices'].message_type = _PROTOMATRIX
DESCRIPTOR.message_types_by_name['ProtoSquare'] = _PROTOSQUARE
DESCRIPTOR.message_types_by_name['ProtoMatrix'] = _PROTOMATRIX
DESCRIPTOR.message_types_by_name['ProtoAllMatrices'] = _PROTOALLMATRICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoSquare = _reflection.GeneratedProtocolMessageType('ProtoSquare', (_message.Message,), {

  'Coordinate' : _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
    'DESCRIPTOR' : _PROTOSQUARE_COORDINATE,
    '__module__' : 'Matrix_pb2'
    # @@protoc_insertion_point(class_scope:ProtoSquare.Coordinate)
    })
  ,
  'DESCRIPTOR' : _PROTOSQUARE,
  '__module__' : 'Matrix_pb2'
  # @@protoc_insertion_point(class_scope:ProtoSquare)
  })
_sym_db.RegisterMessage(ProtoSquare)
_sym_db.RegisterMessage(ProtoSquare.Coordinate)

ProtoMatrix = _reflection.GeneratedProtocolMessageType('ProtoMatrix', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMATRIX,
  '__module__' : 'Matrix_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMatrix)
  })
_sym_db.RegisterMessage(ProtoMatrix)

ProtoAllMatrices = _reflection.GeneratedProtocolMessageType('ProtoAllMatrices', (_message.Message,), {
  'DESCRIPTOR' : _PROTOALLMATRICES,
  '__module__' : 'Matrix_pb2'
  # @@protoc_insertion_point(class_scope:ProtoAllMatrices)
  })
_sym_db.RegisterMessage(ProtoAllMatrices)


# @@protoc_insertion_point(module_scope)
