# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solvedPuzzle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='solvedPuzzle.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12solvedPuzzle.proto\"\x18\n\x06Puzzle\x12\x0e\n\x06puzzle\x18\x01 \x01(\tb\x06proto3')
)




_PUZZLE = _descriptor.Descriptor(
  name='Puzzle',
  full_name='Puzzle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='puzzle', full_name='Puzzle.puzzle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['Puzzle'] = _PUZZLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Puzzle = _reflection.GeneratedProtocolMessageType('Puzzle', (_message.Message,), {
  'DESCRIPTOR' : _PUZZLE,
  '__module__' : 'solvedPuzzle_pb2'
  # @@protoc_insertion_point(class_scope:Puzzle)
  })
_sym_db.RegisterMessage(Puzzle)


# @@protoc_insertion_point(module_scope)
