# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solvedPuzzle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='solvedPuzzle.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12solvedPuzzle.proto\">\n\tSolutions\x12\x17\n\x0fnumberOfPuzzles\x18\x01 \x01(\x05\x12\x18\n\x07puzzles\x18\x02 \x03(\x0b\x32\x07.Puzzle\"0\n\x06Puzzle\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x18\n\x07squares\x18\x02 \x03(\x0b\x32\x07.Square\"-\n\x06Square\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\x62\x06proto3')
)




_SOLUTIONS = _descriptor.Descriptor(
  name='Solutions',
  full_name='Solutions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numberOfPuzzles', full_name='Solutions.numberOfPuzzles', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='puzzles', full_name='Solutions.puzzles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=84,
)


_PUZZLE = _descriptor.Descriptor(
  name='Puzzle',
  full_name='Puzzle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='Puzzle.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squares', full_name='Puzzle.squares', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=134,
)


_SQUARE = _descriptor.Descriptor(
  name='Square',
  full_name='Square',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Square.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Square.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Square.value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=181,
)

_SOLUTIONS.fields_by_name['puzzles'].message_type = _PUZZLE
_PUZZLE.fields_by_name['squares'].message_type = _SQUARE
DESCRIPTOR.message_types_by_name['Solutions'] = _SOLUTIONS
DESCRIPTOR.message_types_by_name['Puzzle'] = _PUZZLE
DESCRIPTOR.message_types_by_name['Square'] = _SQUARE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Solutions = _reflection.GeneratedProtocolMessageType('Solutions', (_message.Message,), {
  'DESCRIPTOR' : _SOLUTIONS,
  '__module__' : 'solvedPuzzle_pb2'
  # @@protoc_insertion_point(class_scope:Solutions)
  })
_sym_db.RegisterMessage(Solutions)

Puzzle = _reflection.GeneratedProtocolMessageType('Puzzle', (_message.Message,), {
  'DESCRIPTOR' : _PUZZLE,
  '__module__' : 'solvedPuzzle_pb2'
  # @@protoc_insertion_point(class_scope:Puzzle)
  })
_sym_db.RegisterMessage(Puzzle)

Square = _reflection.GeneratedProtocolMessageType('Square', (_message.Message,), {
  'DESCRIPTOR' : _SQUARE,
  '__module__' : 'solvedPuzzle_pb2'
  # @@protoc_insertion_point(class_scope:Square)
  })
_sym_db.RegisterMessage(Square)


# @@protoc_insertion_point(module_scope)
